export const PERMISSIONS = {
  CUSTOMERS_VIEW: 'customers.view',
  CUSTOMERS_MANAGE: 'customers.manage',
  PROVIDERS_VIEW: 'providers.view',
  PROVIDERS_MANAGE: 'providers.manage',
  PROVIDERS_VERIFY: 'providers.verify',
  FLEET_VIEW: 'fleet.view',
  FLEET_MANAGE: 'fleet.manage',
  DRIVERS_VIEW: 'drivers.view',
  DRIVERS_MANAGE: 'drivers.manage',
  SHIPMENTS_VIEW: 'shipments.view',
  SHIPMENTS_CREATE: 'shipments.create',
  SHIPMENTS_MANAGE: 'shipments.manage',
  QUOTATIONS_VIEW: 'quotations.view',
  QUOTATIONS_CREATE: 'quotations.create',
  QUOTATIONS_MANAGE: 'quotations.manage',
  QUOTATIONS_ACCEPT: 'quotations.accept',
  JOBS_VIEW: 'jobs.view',
  JOBS_MANAGE: 'jobs.manage',
  TRIPS_VIEW: 'trips.view',
  TRIPS_ASSIGN: 'trips.assign',
  TRIPS_UPDATE: 'trips.update',
  TRACKING_VIEW: 'tracking.view',
  POD_VIEW: 'pod.view',
  POD_CREATE: 'pod.create',
  PAYMENTS_VIEW: 'payments.view',
  PAYMENTS_MANAGE: 'payments.manage',
  INVOICES_VIEW: 'invoices.view',
  SETTLEMENTS_VIEW: 'settlements.view',
  SETTLEMENTS_REQUEST: 'settlements.request',
  SETTLEMENTS_MANAGE: 'settlements.manage',
  WALLETS_VIEW: 'wallets.view',
  WALLETS_MANAGE: 'wallets.manage',
  REPORTS_VIEW: 'reports.view',
  USERS_MANAGE: 'users.manage',
  ROLES_MANAGE: 'roles.manage',
  COMPANY_MANAGE: 'company.manage',
  DASHBOARD_VIEW: 'dashboard.view',
} as const

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]

export const PERMISSION_GROUPS = [
  { id: 'overview', keys: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.REPORTS_VIEW] },
  {
    id: 'directory',
    keys: [
      PERMISSIONS.CUSTOMERS_VIEW,
      PERMISSIONS.CUSTOMERS_MANAGE,
      PERMISSIONS.PROVIDERS_VIEW,
      PERMISSIONS.PROVIDERS_MANAGE,
      PERMISSIONS.PROVIDERS_VERIFY,
    ],
  },
  {
    id: 'fleet',
    keys: [PERMISSIONS.FLEET_VIEW, PERMISSIONS.FLEET_MANAGE, PERMISSIONS.DRIVERS_VIEW, PERMISSIONS.DRIVERS_MANAGE],
  },
  {
    id: 'operations',
    keys: [
      PERMISSIONS.SHIPMENTS_VIEW,
      PERMISSIONS.SHIPMENTS_CREATE,
      PERMISSIONS.SHIPMENTS_MANAGE,
      PERMISSIONS.QUOTATIONS_VIEW,
      PERMISSIONS.QUOTATIONS_CREATE,
      PERMISSIONS.QUOTATIONS_MANAGE,
      PERMISSIONS.QUOTATIONS_ACCEPT,
      PERMISSIONS.JOBS_VIEW,
      PERMISSIONS.JOBS_MANAGE,
      PERMISSIONS.TRIPS_VIEW,
      PERMISSIONS.TRIPS_ASSIGN,
      PERMISSIONS.TRIPS_UPDATE,
      PERMISSIONS.TRACKING_VIEW,
      PERMISSIONS.POD_VIEW,
      PERMISSIONS.POD_CREATE,
    ],
  },
  {
    id: 'finance',
    keys: [
      PERMISSIONS.PAYMENTS_VIEW,
      PERMISSIONS.PAYMENTS_MANAGE,
      PERMISSIONS.INVOICES_VIEW,
      PERMISSIONS.SETTLEMENTS_VIEW,
      PERMISSIONS.SETTLEMENTS_REQUEST,
      PERMISSIONS.SETTLEMENTS_MANAGE,
      PERMISSIONS.WALLETS_VIEW,
      PERMISSIONS.WALLETS_MANAGE,
    ],
  },
  {
    id: 'admin',
    keys: [PERMISSIONS.USERS_MANAGE, PERMISSIONS.ROLES_MANAGE, PERMISSIONS.COMPANY_MANAGE],
  },
] as const
